

CREATE TABLE IF NOT EXISTS prices (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      brand_id INTEGER NOT NULL,
                                      start_date TIMESTAMP NOT NULL,
                                      end_date TIMESTAMP NOT NULL,
                                      price_list INTEGER NOT NULL,
                                      product_id INTEGER NOT NULL,
                                      priority INTEGER NOT NULL,
                                      price DECIMAL(10,2) NOT NULL,
                                      currency VARCHAR(3) DEFAULT 'EUR'
    );

CREATE INDEX IF NOT EXISTS IDX_PRICES_BRAND_PRODUCT_DATES
    ON prices (brand_id, product_id, start_date, end_date);