spring:
  application:
    name: assessment-ddd

  cache:
    type: hazelcast

  datasource:
    url: jdbc:h2:mem:assessment
    username: user-assessment
    password: pwd-assessment

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:01_schema.sql
      data-locations: classpath:01_data.sql
      continue-on-error: false

management:
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    root: INFO
    com.example.assessmentddd: DEBUG

springdoc:
  api-docs:
    enabled: true
